application: udacity-web-development-253
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /unit2/rot13
  script: rot13.app

- url: /unit3/.*
  script: blog.app

- url: /unit4/.*
  script: auth.app

- url: /unit5/.*
  script: api.app

- url: /unit6/.*
  script: cache.app

- url: /.*
  script: helloworld.app


libraries:
- name: jinja2
  version: latest

